# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [4]:
A = np.arange(1, 16).reshape(3,5)

print("Axes: ", A.ndim, "\nShape: ", A.shape, "\nSize: ", A.size, "\nDatatype: ", A.dtype.name)


Axes:  2 
Shape:  (3, 5) 
Size:  15 
Datatype:  int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print("\nElementwise subtraction: ")
print(B-C)
print("\nElementwise multiplication: ")
print(B*C)
print("\nMatrix multiplication: ")
print(B@C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise subtraction: 
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication: 
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication: 
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

print("\nExponentiated elementwise: \n", np.exp(B))

print("\nMinimum value: ", B.min())

print("\nMinimum value per row: ", B.min(axis=1))

print("\nMinimum value per column: ", B.min(axis=0))

print("\nIndex for minimum value in whole matrix: ", B.argmin())

print("\nIndex for minimum value per row: ", np.argmin(B,axis=1))

print("\nSum of all elements: ", B.sum())

print("\nMean for each column: ", B.mean(axis=0))

print("\nMedian for each column: ", np.median(B, axis=0))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiated elementwise: 
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value:  1

Minimum value per row:  [1 4 7]

Minimum value per column:  [1 2 3]

Index for minimum value in whole matrix:  0

Index for minimum value per row:  [0 0 0]

Sum of all elements:  45

Mean for each column:  [4. 5. 6.]

Median for each column:  [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
A[1]


array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
The missing indice is assumed to be there, equalling ':' as in A[1,:]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [24]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [27]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
A one dimensional array is created with 30 elements
The array is reshaped into a three dimensional array with three arguments: 2 for no of matrices, 3 for no of rows per matrice, and -1 means the no of columns are automatically calculated.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [28]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [29]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [30]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [ ]:
#import numpy as np

def add_mult_matrices(m1, m2, operation):
    if isinstance(m1,np.ndarray) == False or isinstance(m2,np.ndarray) == False:
        print("Please enter two matrices to operate on.")
        return
    #print(m1.shape)
    #print(m2.shape)
    
    match operation:
        # Check if we are adding or multiplying
        case "add":
            # Operation is add, check that the matrices are the same size
            if m1.shape == m2.shape:
                return m1 + m2
            else:
                print("Please make sure the matrices are the same size when doing addition!")
        
        case "multiply":
            # Operation is multiply, check that matrix dimensions are valid:
            # No of columns in m1 must equal no of rows in m2 (and vice versa)
            if (m1.shape[1] != m2.shape[0]) or (m1.shape[0] != m2.shape[1]):
                print("Please make sure to use valid matrix dimensions!")
                return
            else:
                return "Element wise multiplication", m1 * m2 ,"Matrix wise multiplication", m1 @ m2
        case _:
            print("Please enter 'add' or 'multiply' for operation.")
            return

#testing
m1 = np.array([[1, 2, 3], [8, 7, 6], [8, 7, 6]])
m2 = np.array([[4, 5, 6], [9, 3, 4], [9, 3, 4]])
#m1 = np.array([[1, 2, 3], [8, 7, 6]])
#m2 = np.array([[4, 5, 6], [9, 3, 4]])
#m1 = np.array([[1, 2], [8, 7]])
#m2 = np.array([[4, 5], [9, 3]])

#m2 = np.array([4,])
#operation="add"
operation="multiply"

add_mult_matrices(m1,m2,operation)

('Element wise multiplication',
 array([[ 4, 10, 18],
        [72, 21, 24],
        [72, 21, 24]]),
 'Matrix wise multiplication',
 array([[ 49,  20,  26],
        [149,  79, 100],
        [149,  79, 100]]))

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [ ]:
10.1.1
a) 1x2
b) 5*(4,3) = (20,15)
c) 3*(4,3) = (12,9)
d) (20,15) + (12,9) = (32,24)
e) (32,24)
f) (16,12) - (4,3) = (12,9)
g) x = (4)
       (3)
h) Nej, olika dimensioner
i) ||x|| = sqrt(4^2 + 3^2) = 5

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [ ]:
10.2.1:
 A= A2x3, B=2x3, C=2x2, D=2x2, E=2,1, I=2x2

a) ej definierat
b) ej definierat
c) ej definierat
d) 2D - 3C = [3 2]
             [2 3]
e) DT + 2D = [9 12]
             [12 9]
f) 2CT - 2DT = [-4 -4]
               [-4 -4]
g) AT - B = [5 2]
            [3 4]
h) ej definierat
i) CD = [3 8]
        [8 3]
j) ej definierat
k) CI = [1 0]
        [0 1]
l) ABT = [5 6]
         [7 4]

10.2.2:
 A = A2x3
 AAT = [29 26]
       [26 42]

10.2.3:
A = 2x2
B = 2x2
c = 2x2

Förstår inte vad som avses?

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

v1.base  # None
v2.base

[0 1 2 3]
[2 3]


array([0, 1, 2, 3])

In [33]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [34]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
